---
title: "check_new_runs_8nov21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, prompt = FALSE, eval = TRUE, 
                      warning = TRUE, comment=NA, cache = FALSE,
                      fig.width = 15, fig.height = 8)

library(dplyr)
library(Seurat)
library(tinytex)
library(patchwork)
library(ggplot2)
options(Seurat.memsafe = TRUE)

```


# All samples


```{r}
Mm_markers <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_integrated_markers.rds")
Mm_umap <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_integrated.rds")
```

```{r}
DimPlot(Mm_umap, reduction = "umap", group.by = "sample")
DimPlot(Mm_umap, reduction = "umap", group.by = "geno", label = TRUE, repel = TRUE)
DimPlot(Mm_umap, reduction = "umap", label = TRUE)
```

```{r}
top_markers <- Mm_markers %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
DoHeatmap(Mm_umap, features = top_markers$gene) + NoLegend()
```

```{r}
FeaturePlot(Mm_umap, features = c("ENSMUSG00000027168"))

```

```{r}
DotPlot(Mm_umap, features = top_markers$gene) + RotatedAxis()
RidgePlot(Mm_umap, features = top_markers$gene)

```


```{r}
rm(Mm_umap)
gc()
```

# Two samples



```{r}
Mm_umap_subset <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_subset_integrated.rds")
Mm_markers_subset <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_subset_integrated_markers.rds")
```


```{r}
DimPlot(Mm_umap_subset, reduction = "umap", group.by = "sample")
DimPlot(Mm_umap_subset, reduction = "umap", group.by = "geno", label = TRUE, repel = TRUE)
DimPlot(Mm_umap_subset, reduction = "umap", label = TRUE)
```

```{r}
top_markers_subset <- Mm_markers_subset %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(Mm_umap_subset, features = top_markers_subset$gene) + NoLegend()
```


```{r}
FeaturePlot(Mm_umap_subset, features = c("ENSMUSG00000027168"))
```


```{r}
DotPlot(Mm_umap_subset, features = top_markers_subset$gene) + RotatedAxis()
RidgePlot(Mm_umap_subset, features = top_markers_subset$gene)

```

# Marker comparison 

```{r}
markers_aj_subset <- readRDS("../data_raw/scmm_project/Analysis/Mm_umap_integrated_markers_subset.rds")
top_markers_aj_subset <- markers_aj_subset %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)

markers_subset_previous_run <- readRDS("../data_output/surat_objects/Mm_umap_integrated_markers_subset.rds")
top_markers_subset_previous_run <- markers_subset_previous_run %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)

```

```{r}
library(UpSetR)
upset(fromList(list("previous"=top_markers_subset_previous_run$gene,"new"=top_markers_subset$gene)))

upset(fromList(list("aj"=top_markers_aj_subset$gene,"new"=top_markers_subset$gene)))

upset(fromList(list("aj"=top_markers_aj_subset$gene,"previous"=top_markers_subset_previous_run$gene)))

```
```{r}
markers_aj_subset %>%
  ggplot(aes(p_val_adj)) +
  geom_histogram(bins = 10)
```
```{r}
markers_aj_subset %>%
  ggplot(aes(avg_logFC)) +
  geom_histogram(bins = 10)

```
```{r}
markers_aj_subset %>%
  ggplot(aes(cluster,p_val_adj)) +
  geom_boxplot()

markers_subset_previous_run %>%
  ggplot(aes(cluster,p_val_adj)) +
  geom_boxplot()

Mm_markers_subset %>%
  ggplot(aes(cluster,p_val_adj)) +
  geom_boxplot()

```

```{r}
markers_aj_subset %>%
  ggplot(aes(cluster,avg_logFC)) +
  geom_boxplot()

markers_subset_previous_run %>%
  ggplot(aes(cluster,avg_log2FC)) +
  geom_boxplot()

Mm_markers_subset %>%
  ggplot(aes(cluster,avg_log2FC)) +
  geom_boxplot()

```

