---
title: "extreme_pseudobulk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE, warning = FALSE)

library(scater)
library(scran)
library(edgeR)
library(Seurat)
library(tidyverse)
options(Seurat.memsafe = TRUE)

```


```{r}
sce_obj <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_mito_integrated.rds")

DefaultAssay(sce_obj) <- "RNA"


sce_obj <- SingleCellExperiment(assays = list(counts = sce_obj@assays$RNA@counts), 
                           colData = DataFrame(sce_obj@meta.data))


```



Aggregate cells per sample to get pseudobulk.

```{r}
# Using 'label' and 'sample' as our two factors; each column of the output
# corresponds to one unique combination of these two factors.
summed <- aggregateAcrossCells(sce_obj, 
    id=colData(sce_obj)[,c("sample")])
summed$batch <- substr(summed$sample,3,3)
```


```{r}
# Creating up a DGEList object for use in edgeR:
library(edgeR)

current <- summed
y <- DGEList(counts(current), samples=colData(current))
# Filter low abundance 

keep <- filterByExpr(y, group=current$geno)
y <- y[keep,]

# Correction for composition and library size biases
y <- calcNormFactors(y)

# Design matrix
design <- model.matrix(~ batch, y$samples)
# Estimate dipersions
y <- estimateDisp(y,robust = T,design = design)

# Fit model
fit <- glmQLFit(y, design, robust=TRUE)
# Test coefficients
res <- glmQLFTest(fit, coef=ncol(design))

summary(decideTests(res))

```
```{r}
plotMDS(y)
```


```{r}
topTags(res,n = Inf)$table %>%
  ggplot(aes(logFC, - 10 * log10(FDR), color = FDR < 0.05)) +
  geom_point() +
  theme(aspect.ratio = 1)
  
```
```{r}
library(clusterProfiler)
library(org.Mm.eg.db)
ensembl_gene_ids_df <- 
drop_na() %>%
  pull(ENTREZID) %>%
  enrichGO(OrgDb = org.Mm.eg.db,keyType = "ENTREZID")


topTags(res,n = Inf)$table %>%
  filter( FDR < 0.05, logFC < -0.5) %>%
  rownames() %>%
  substr(1,18) %>%
  bitr(fromType = "ENSEMBL",toType = c("ENTREZID"),OrgDb = org.Mm.eg.db) %>%
  pull(ENTREZID) %>%
  enrichGO(OrgDb = org.Mm.eg.db,keyType = "ENTREZID") %>%
  barplot()

  
```

```{r}
topTags(res,n = Inf)$table %>%
  filter( FDR < 0.05, logFC < -0.5) %>%
  rownames() %>%
  substr(1,18) %>%
  bitr(fromType = "ENSEMBL",toType = c("SYMBOL"),OrgDb = org.Mm.eg.db) 

```

