---
title: "litter2_analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(tidyverse)
options(Seurat.memsafe = TRUE)
```

# Read seurat object
```{r}
seurat_obj <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_subset_mito_integrated.rds")

```

# Clustering
```{r eval = FALSE}
DefaultAssay(seurat_obj) <- "integrated"
seurat_obj <- FindNeighbors(object = seurat_obj, dims = 1:20)
seurat_obj <- FindClusters(object = seurat_obj, resolution = 1.1)

```
```{r eval = FALSE}
saveRDS(seurat_obj$integrated_snn_res.1.1, "../data_output/surat_objects/run_8nov21/Mm_merged_mito_subset_mito_integrated_clusters.rds")
```

```{r}
seurat_obj$integrated_snn_res.1.1 <- readRDS( "../data_output/surat_objects/run_8nov21/Mm_merged_mito_subset_mito_integrated_clusters.rds")
seurat_obj$seurat_clusters <- seurat_obj$integrated_snn_res.1.1
```

# UMAP 
```{r}
DimPlot(seurat_obj,label = TRUE,group.by = "geno") +
  theme(aspect.ratio = 1)
```

# Integrated markers 
```{r eval = FALSE}
DefaultAssay(seurat_obj) <- "RNA"
seurat_obj <- NormalizeData(seurat_obj)

seurat_obj_conserved_markers_list <- lapply(levels(Idents(seurat_obj)), FindConservedMarkers, object = seurat_obj,grouping.var = "geno", verbose = FALSE )

saveRDS(seurat_obj_conserved_markers_list, "../data_output/surat_objects/litter2_conserved_markers_list.rds")

names(seurat_obj_conserved_markers_list) <- levels(Idents(seurat_obj))

seurat_obj_conserved_markers_list_df <- do.call(rbind,imap(seurat_obj_conserved_markers_list, function(.x,.y) {
  .x <- rownames_to_column(.x,var = "ensembl")
  .x$cluster <- .y
  return(.x)
}))

saveRDS(seurat_obj_conserved_markers_list_df, "../data_output/surat_objects/litter2_conserved_markers_list_df.rds")

```

```{r eval = FALSE}
top30_markers <- seurat_obj_conserved_markers_list_df %>%
  group_by(cluster) %>%
  top_n(30,XP_avg_log2FC)

library(clusterProfiler)
library(org.Mm.eg.db)

symbol_map <- bitr(top30_markers$ensembl,fromType = "ENSEMBL",toType = "SYMBOL",OrgDb = org.Mm.eg.db)

symbol_map <- symbol_map[!duplicated(symbol_map$ENSEMBL),]

top30_markers <- left_join(top30_markers,symbol_map, by =c("ensembl" = "ENSEMBL"))

write.csv(top30_markers, "../data_output/surat_objects/litter2_top30lfc_markers.csv")

```



# Tbr2
```{r}
library(clusterProfiler)
library(org.Mm.eg.db)

tbr2 <- bitr("Eomes",fromType = "SYMBOL",toType = "ENSEMBL",OrgDb = org.Mm.eg.db)$ENSEMBL

FeaturePlot(object = seurat_obj,features = tbr2) +
  theme(aspect.ratio = 1) 

VlnPlot(object = seurat_obj, features = tbr2) +
  theme(aspect.ratio = 0.75)
```

# Fzd8 
```{r}
DefaultAssay(seurat_obj) <- "RNA"
seurat_obj <- NormalizeData(seurat_obj)

fzd8 <- bitr("Fzd8",fromType = "SYMBOL",toType = "ENSEMBL",OrgDb = org.Mm.eg.db)$ENSEMBL

FeaturePlot(object = seurat_obj,features = fzd8) +
  theme(aspect.ratio = 1)

VlnPlot(object = seurat_obj, features = fzd8,sort = "ascending",pt.size = 0) +
  theme(aspect.ratio = 0.75, legend.position = "none")


VlnPlot(object = seurat_obj, features = fzd8,sort = "ascending",pt.size = 0,split.by = "geno") +
  theme(aspect.ratio = 0.75, legend.position = "none")

VlnPlot(object = seurat_obj, features = fzd8,sort = "ascending",pt.size = 0,group.by  = "geno") +
  theme(aspect.ratio = 0.75, legend.position = "none")
```

```{r}


wilcox.test(x = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "WT"],y = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "XP"])


```


```{r}
rbind(data.frame("fzd8" = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "WT"],
           "geno" = "WT") ,
      data.frame("fzd8" = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "XP"],
           "geno" = "HARE5")) %>%
  ggplot(aes(geno,fzd8)) +
  geom_jitter() +
  geom_violin() 
```


```{r}
wilcox.test(x = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "WT"],y = seurat_obj@assays$RNA@data[fzd8,seurat_obj$geno == "XP"])
```


# Malat
```{r}

malat1 <- bitr("Malat1",fromType = "SYMBOL",toType = "ENSEMBL",OrgDb = org.Mm.eg.db)$ENSEMBL

seurat_obj$malat_percent <- PercentageFeatureSet(seurat_obj,features = malat1)

FeaturePlot(object = seurat_obj,features = "malat_percent") +
  theme(aspect.ratio = 1)

VlnPlot(object = seurat_obj, features = "malat_percent") +
  theme(aspect.ratio = 1)
```

# Differential abundance 
```{r}
counts_plot <- seurat_obj@meta.data %>%
  as_data_frame() %>%
  ggplot(aes(seurat_clusters, fill =  geno)) +
  geom_bar(position = "dodge") +
  scale_fill_brewer(type = "qual",palette = 7) +
  theme_minimal()


```

```{r}
tabled_n_by_clust <- table(seurat_obj@meta.data$seurat_clusters,seurat_obj@meta.data$geno)
relative_tabled_n_by_clust <- tabled_n_by_clust
relative_tabled_n_by_clust[,"WT"] <- relative_tabled_n_by_clust[,"WT"]/sum(relative_tabled_n_by_clust[,"WT"])
relative_tabled_n_by_clust[,"XP"] <- relative_tabled_n_by_clust[,"XP"]/sum(relative_tabled_n_by_clust[,"XP"])

prop_plot <- as.data.frame(relative_tabled_n_by_clust) %>%
  mutate(seurat_clusters = Var1,
         geno = Var2) %>%
  ggplot(aes(seurat_clusters,Freq, fill =  geno)) +
  geom_col(position = "dodge") +
  scale_fill_brewer(type = "qual",palette = 7) + 
  theme_minimal() +
  ylab("Proportion")

```

```{r}
(counts_plot / prop_plot) + patchwork::plot_layout(guides = "collect")
```


EdgeR
```{r}
library(scater)
library(edgeR)
sce_obj <- as.SingleCellExperiment(seurat_obj)

abundances <- table(seurat_obj@meta.data$seurat_clusters,seurat_obj@meta.data$sample)

abundances <- unclass(abundances) 


extra_info <- colData(sce_obj)[match(colnames(abundances), sce_obj$sample),]

extra_info$geno <- factor(extra_info$geno)
y_ab <- DGEList(abundances, samples=extra_info)

design <- model.matrix(~ geno, y_ab$samples)

y_ab <- calcNormFactors(y_ab)

fit_ab <- exactTest(y_ab,dispersion = 0.2)
fit_ab$table
```
```{r}
topTags(fit_ab,n = Inf )$table %>%
  ggplot(aes(x = 1,y = logFC)) +
      geom_boxplot(outlier.shape=NA) +
  geom_jitter() +
  theme_minimal() +
  theme(aspect.ratio = 4) +
  xlab(NULL)

```
```{r}
topTags(fit_ab,n = Inf )$table %>%
  ggplot(aes(x = 1,y = logFC)) +
      geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  theme_minimal() +
  theme(aspect.ratio = 4) +
  xlab(NULL) +
  geom_hline(yintercept = 0.5, color = "red",lty=3) +
  geom_hline(yintercept = - 0.5, lty =3) 

```

```{r}

extreme_hare5_plot <- as.data.frame(relative_tabled_n_by_clust) %>%
  mutate(seurat_clusters = Var1,
         geno = Var2) %>%
  filter(seurat_clusters %in% rownames(fit_ab$table[fit_ab$table$logFC > 0.5,])) %>%
  ggplot(aes(seurat_clusters,Freq, fill =  geno)) +
  geom_col(position = "dodge") +
  scale_fill_brewer(type = "qual",palette = 7) +
  theme_minimal() +
  theme(aspect.ratio = 1)

```
```{r}
extreme_wt_plot <- as.data.frame(relative_tabled_n_by_clust) %>%
  mutate(seurat_clusters = Var1,
         geno = Var2) %>%
  filter(seurat_clusters %in% rownames(fit_ab$table[fit_ab$table$logFC < - 0.5,])) %>%
  ggplot(aes(seurat_clusters,Freq, fill =  geno)) +
  geom_col(position = "dodge") +
  scale_fill_brewer(type = "qual",palette = 7) +
  theme_minimal() +
  theme(aspect.ratio = 1)

```
```{r}
(extreme_hare5_plot | extreme_wt_plot) + patchwork::plot_layout(guides = "collect")
```

# Differential expression
```{r}
library(scran)
library(scater)
sce_obj <- SingleCellExperiment(assays = list(counts = seurat_obj@assays$RNA@counts), 
                           colData = DataFrame(seurat_obj@meta.data))
summed <- aggregateAcrossCells(sce_obj, 
    id=colData(sce_obj)[,c("seurat_clusters","sample")])


# Creating up a DGEList object for use in edgeR:
library(edgeR)

pseudoBulkDGEExact <- function(label, summed) {
  
  current <- summed[,label==summed$seurat_clusters]

  y <- DGEList(counts(current), samples=colData(current))
  # Filter low abundance 
  keep <- filterByExpr(y, group=current$geno)
  y <- y[keep,]
  
  # Correction for composition and library size biases
  y <- calcNormFactors(y)
  
  # Exact test
  y <- exactTest(y,dispersion = 0.2^2)
  
  # Test coefficients
  top_res <- topTags(y,n = Inf)
  return(top_res$table)
}


de_per_clust <- map(unique(summed$seurat_clusters), pseudoBulkDGEExact, summed = summed)
names(de_per_clust) <- unique(summed$seurat_clusters)
```

```{r}
lognormsummed <- summed
sizeFactors(lognormsummed) <- NULL
lognormsummed <- logNormCounts(lognormsummed)

```

```{r}
de_results_df <- do.call(rbind,lapply(names(de_per_clust),
      function(title,x) {
        x <- x[[title]]
        x <- as.data.frame(x)
        x$cluster <- title
        x <- x %>%
          rownames_to_column(var = "ENSEMBL")
        return(x)
      }, x = de_per_clust))

ens2symbol <- clusterProfiler::bitr(de_results_df$ENSEMBL,fromType = "ENSEMBL",toType = "SYMBOL",OrgDb = org.Mm.eg.db)

de_results_df <- left_join(de_results_df, ens2symbol,by= "ENSEMBL")
de_results_df <- drop_na(de_results_df)
```

```{r}
ambient_matrix <- readRDS(file = "../data_output/osca_objects/ambient_matrix.Rds")
ambient_matrix <- ambient_matrix[,c(2,4)]
  summed <- summed[rownames(summed) %in% rownames(ambient_matrix),]
  
  ambient_matrix <- ambient_matrix[rownames(summed), ]

library(DropletUtils)
maxambients_per_clust <- map(unique(summed$seurat_clusters),function(.x, summed, ambient){
  current_summed <- summed[,summed$seurat_clusters == .x]
  
  current_max_ambient <- ambientContribMaximum(counts(current_summed), 
                                               ambient_matrix, mode="proportion")
  
  
  
  currentcontamination <- rowMeans(current_max_ambient, na.rm=TRUE)
  return(currentcontamination)
}, summed = summed, ambient = ambient_matrix)


names(maxambients_per_clust) <- unique(summed$seurat_clusters)

de_results_df_list <- lapply(names(de_per_clust),
      function(clust,de_df, ambient_mat) {
        x <- de_df[[clust]]
        contamination <- ambient_mat[[clust]]
        x <- as.data.frame(x)
        x$cluster <- clust
        x$contamination <- contamination[rownames(x)]
        x <-rownames_to_column(x,var = "ENSEMBL")
        
        return(x)
      }, de_df = de_per_clust, ambient_mat = maxambients_per_clust)

de_results_df <- do.call(rbind,de_results_df_list)

ens2symbol <- clusterProfiler::bitr(de_results_df$ENSEMBL,fromType = "ENSEMBL",toType = "SYMBOL",OrgDb = org.Mm.eg.db)

de_results_df <- left_join(de_results_df, ens2symbol,by= "ENSEMBL")
de_results_df <- drop_na(de_results_df)

```



```{r}
de_results_df %>%
  ggplot(aes(logCPM, logFC, color = FDR < 0.05 & contamination < 0.05)) +
  geom_point(size = 0.5, pch = 1) +
  scale_color_manual(values = c("TRUE" = "red","FALSE"="darkgray")) +
  theme_light() +
  theme(aspect.ratio = 1) +
  facet_wrap(~cluster) +
  ggrepel::geom_text_repel(mapping = aes(label = SYMBOL),
                           data = de_results_df %>%
                             filter(FDR < 0.05 & contamination < 0.05),
                           color = "black",
                           max.overlaps = 30,
                           size = 3) 

```
```{r}
de_results_df %>%
  ggplot(aes(logFC, -10 * log10(FDR), color = FDR < 0.05)) +
  geom_point(size = 0.5, pch = 1) +
  scale_color_manual(values = c("TRUE" = "red","FALSE"="darkgray")) +
  facet_wrap(vars(cluster)) +
  geom_hline(yintercept = -10 * log10(0.05), color = "red", linetype = "dashed" ) +
  ylim(c(0,50)) %>%
  theme_light() +
  theme(aspect.ratio = 1) +
  ggrepel::geom_text_repel(mapping = aes(label = SYMBOL),data = de_results_df %>%
                             filter(FDR < 0.05),color = "black",max.overlaps = 30, size = 3) 

```

```{r}
de_results_df %>%
  filter(cluster == "14") %>%
  ggplot(aes(logFC, -10 * log10(FDR), color = FDR < 0.05)) +
  geom_point(size = 0.5, pch = 1) +
  scale_color_manual(values = c("TRUE" = "red","FALSE"="darkgray")) +
  geom_hline(yintercept = -10 * log10(0.05), color = "red", linetype = "dashed" ) +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggrepel::geom_text_repel(mapping = aes(label = SYMBOL),data = de_results_df %>%
                             filter(FDR < 0.05, cluster == "14"),color = "black",max.overlaps = 30, size = 3) 

```


# Cel cycle

## Run cyclone
```{r eval = FALSE}
set.seed(100)

library(scran)
mm.pairs <- readRDS(system.file("exdata", "mouse_cycle_markers.rds", 
    package="scran"))

# Using Ensembl IDs to match up with the annotation in 'mm.pairs'.
assignments <- cyclone(sce_obj, mm.pairs, gene.names=rownames(sce_obj))
plot(assignments$score$G1, assignments$score$G2M,
    xlab="G1 score", ylab="G2/M score", pch=16)
saveRDS(assignments,"../data_output/osca_objects/cellcycle_assignments_litter2.rds")
```

```{r}
assignments <- readRDS("../data_output/osca_objects/cellcycle_assignments_litter2.rds")
seurat_obj$G1 <- assignments$normalized.scores$G1
seurat_obj$S <- assignments$normalized.scores$S
seurat_obj$G2M <- assignments$normalized.scores$G2M
seurat_obj$phases <- assignments$phases

```

```{r}
FeaturePlot(seurat_obj,features = "G1")

```
```{r}
FeaturePlot(seurat_obj,features = "G2M")

```
```{r}
FeaturePlot(seurat_obj,features = "S")

```
```{r}
DimPlot(seurat_obj,group.by  = "phases", split.by = "geno") +theme(aspect.ratio = 1) 

```

```{r}

DimPlot(seurat_obj,group.by  = "phases")

```

