---
title: "subcluster_tbr2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
```


```{r}
seurat_obj <- readRDS("../data_output/surat_objects/run_8nov21/Mm_merged_mito_mito_integrated.rds")
```

```{r}
library(clusterProfiler)
library(org.Mm.eg.db)

tbr2_ensembl <- bitr("Eomes",fromType = "SYMBOL",toType = "ENSEMBL",OrgDb =  org.Mm.eg.db)$ENSEMBL
malat_ensembl <- bitr("Malat1",fromType = "SYMBOL",toType = "ENSEMBL",OrgDb =  org.Mm.eg.db)$ENSEMBL


```

```{r}
DefaultAssay(seurat_obj) <- "RNA"

seurat_obj <- NormalizeData(seurat_obj)

VlnPlot(seurat_obj,tbr2_ensembl)
```
```{r}
FeaturePlot(seurat_obj,tbr2_ensembl)

```

```{r}
seurat_obj$percent.malat1 <- PercentageFeatureSet(seurat_obj,features = malat_ensembl,assay = "RNA")

```


```{r}
seurat_obj$tbr2 <- seurat_obj@assays$RNA@data[tbr2_ensembl,]
table(seurat_obj$tbr2 > 0)
table(seurat_obj$percent.malat1 > 5)

```

Filter, get only tbr2 > 1
```{r}
seurat_obj <- seurat_obj[,seurat_obj$tbr2 > 0]
```


Re-do PCA, UMAP and clusters
```{r}
DefaultAssay(seurat_obj) <- "integrated"
seurat_obj <- RunPCA(seurat_obj, verbose = FALSE, npcs = 50)
seurat_obj <- RunUMAP(seurat_obj, reduction = "pca", dims = 1:20)

seurat_obj <- FindNeighbors(object = seurat_obj, dims = 1:20)
seurat_obj <- FindClusters(object = seurat_obj, resolution = 1.1)

```

```{r}
DimPlot(seurat_obj, split.by = "sample")
```

